# Generated by Django 5.2.13 on 2026-05-24 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('host', models.CharField(blank=True, max_length=128, null=True)),
                ('presentation_mode', models.BooleanField(default=False)),
                ('muted_users', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rooms.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'nickname'), name='uniq_roommember_room_nickname')],
            },
        ),
        migrations.CreateModel(
            name='RoomPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='rooms.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'last_seen'], name='rooms_roomp_room_id_141ebb_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'client_id'), name='uniq_roompresence_room_client_id')],
            },
        ),
    ]
