# Generated by GitHub Copilot on 2026-05-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="presentation_mode",
        ),
        migrations.RemoveField(
            model_name="room",
            name="muted_users",
        ),
    ]
