# Generated by Django 5.2.13 on 2026-06-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_presentation_and_muted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice'), ('video', 'Video')], default='chat', max_length=16),
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('message_type', models.CharField(default='chat', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.room')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
